title: JSPerf
description: Community Driven JavaScript Performance Benchmarks
logo: /logo.png

incremental: true

collections:
  benchmarks:
    permalink: /:path
    output: true

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: default
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: benchmarks
    values:
      layout: benchmark

contents:
  benchmarks:
    path: '_benchmarks/:slug.md'
    template: '_templates/benchmark.liquid'
    commit: false

  data:
    path: '_data/:slug/:uuid.yml'
    template: '_templates/data.liquid'
    commit: true

gems:
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-github-metadata
